### ISSUE TITLE
Suspected temporal_resolution error in lag_data()

### ISSUE THREAD

**Issue by mjrutala** [arfogg/generic_MI_lag_finder#1]
In running the following command:

`mi_lag_finder(x1, x2, temporal_resolution=15, max_lag=4320, min_lag=-4320, remove_nan_rows=True)`

where x1 and x2 are numpy arrays with dtype = float64 and length 1296, representing data downsampled to 15-minute intervals; x1 contains NaNs; and temporal_resolution, max_lag, and min_lag set in minutes, I get the following error:

>  File ~/code/python/libraries/generic_MI_lag_finder/generic_mutual_information_routines.py:100 in lag_data
>     lagged_timeseries_b=np.full((end_i-start_i, lags.size), np.nan)
> 
>   File ~/miniconda3/envs/spyder-env/lib/python3.11/site-packages/numpy/core/numeric.py:344 in full
>     a = empty(shape, dtype, order)
> 
> ValueError: negative dimensions are not allowed

I suspect this is because the values of the maximum and minimum time lags (4320) are larger than the length of x1 and x2 (1296), even though the actual duration of the time lags (4,320 minutes) is shorter than the actual duration of the data (19,440 minutes).

Matt

**Comment by arfogg** [comment]
Thanks for the description of your error - I can replicate this on my machine so I'm working on fixing it now!
Alexandra

**Comment by arfogg** [comment]
Ok I think I have fixed this now.

Added consideration of the temporal resolution to the creation of `lagged_timeseries_b` and the indexing of `timeseries_b` in `lag_data`. Please see commit [here](https://github.com/arfogg/generic_MI_lag_finder/commit/db74b68c05ba9332a221769bdc09ae716f35740c).

If you update the code, and give it a test - let me know how you get on!

Alexandra

**Comment by mjrutala** [comment]
The code seems to be working as expected now! Giving a temporal resolution greater than 1 minute, with maximum and minimum shifts still in units of minutes, works.
Thanks!
Matt
