### ISSUE TITLE
requirements.txt file to help the user install the necessary python packages

### ISSUE THREAD

**Issue by CorentinLouis** [arfogg/generic_MI_lag_finder#2]
You should create a requirements.txt file containing all the python packages and their versions, so that users know what needs to be installed, and can then, in a python environment, do a "pip install requirements.txt".

Exemple here if you want:
https://github.com/CorentinLouis/SPACE_labelling_tool/blob/master/requirements.txt

(You should also specify in the README on which python version this code was developped ;-) )

**Comment by arfogg** [comment]
I have (finally!) made these changes.
You can find the requirements file here: https://github.com/arfogg/generic_MI_lag_finder/blob/main/requirements.txt
Python version is in the README.

Thanks for the suggestion Corentin! 

Closing this as it's all sorted.
